# errata:
# - A travis bug causes caches to trample eachother when using the same
#   compiler key (which we don't use anyway). This is worked around for now by
#   replacing the "compilers" with a build name prefixed by the no-op ":"
#   command. See: https://github.com/travis-ci/casher/issues/6

sudo: required
dist: trusty

os: linux
language: cpp
compiler: gcc

env:
  global:
    - MAKEJOBS=-j3
    - RUN_TESTS=false
    - CCACHE_SIZE=100M
    - CCACHE_TEMPDIR=/tmp/.ccache-temp
    - CCACHE_COMPRESS=1
    - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
    - SDK_URL=https://bitcoincore.org/depends-sources/sdks
cache:
  apt: true
  directories:
  - depends/built
  - depends/sdk-sources
  - $HOME/.ccache
matrix:
  fast_finish: true
  include:
    - compiler: ": bitcoind"
      env: HOST=x86_64-unknown-linux-gnu PACKAGES="bc"
  exclude:
    - compiler: gcc
install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y # For g++-4.9
    - sudo apt-get update -qq
    - sudo apt-get install -qq g++-4.9
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
    - sudo apt-get install -qq gdb
    - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get update; fi
    - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq $PACKAGES; fi
before_script:
    - ulimit -c unlimited -S
script:
    #- gcc allocatememory.c -o allocatememory
    #- ./allocatememory & ./allocatememory & ./allocatememory & ./allocatememory ; watch "ps aux | grep allocatememory"
    - ./zcutil/build.sh -j2
    - ./qa/zerocash/full-test-suite.sh
    - echo '=== daemon 0 log (tail 400) ==='; tail -400 ./.zc-system-test/0/stdout.log
    - find ./ -maxdepth 5 -name 'core*' -print
    - for i in $(find ./ -maxdepth 5 -name 'core*' -print); do gdb $(pwd)/src/bitcoind src/core -ex "thread apply all bt" -ex "set pagination 0" -ex "thread apply all x/5i $pc" -batch; done;
