[package]
name = "provisionec2"
version = "0.1.0"
authors = ["Za Wilcox <zancas@protonmail.com>"]
edition = "2018"

[dependencies]
rusoto_ec2 = {version = "0.40.0"}
rusoto_core = {version = "0.40.0"}
