name: CI

on:
  pull_request:
  pull_request_target:
  push:
    branches: master

jobs:

  build:
    name: Build 
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

